name: Build, tag, test
on:
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git branch
          echo "${{ github.event.pull_request.head.ref }}"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.sha }}"
          echo "${{ toJson(github) }}"
          git checkout ${{ github.event.pull_request.head.ref }}
          echo "${{ github.sha }}"
      - uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
          preferLatestVersion: true
      - id: version-step
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true
          configFilePath: gitversion.yml
      - run: |
          echo "semVer: ${{ steps.version-step.outputs.semVer }}"
          echo "preReleaseTag: ${{ steps.version-step.outputs.preReleaseTag }}"
          echo "sha: ${{ steps.version-step.outputs.sha }}"
          echo "shortSha: ${{ steps.version-step.outputs.shortSha }}"
          echo "branchName: ${{ steps.version-step.outputs.branchName }}"
      - name: Build
        id: skiptest
        run: |
          echo "build"
