name: Build Workflow

on:
  workflow_run:
    workflows: ["Test Workflow"]
    types:
      - completed

jobs:
  use-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Use Commit Hash and Run Build Docker
        run: |
          COMMIT_HASH=${{ github.event.workflow_run.head_commit.id }}
          echo "Associate commit hash $COMMIT_HASH to build"
