name: Dependent Workflow

on:
  workflow_run:
    workflows: ["Tag, build, test"]
    types:
      - completed

jobs:
  use-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Use Commit Hash and Tag
        run: |
          COMMIT_HASH=${{ github.event.workflow_run.head_commit.id }}
          echo "Using commit hash $COMMIT_HASH"
