name: Simulate Concurrent PR Merges

on:
  schedule:
    - cron: '17 21 * * *'  # Runs at 1:50 PM Eastern Time 
  
env:
  GH_TOKEN: ${{ secrets.FRACTIONS_SECRET }}

permissions:
  contents: write
  pull-requests: write

jobs:
  simulate_concurrent_merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Merge pull requests
        run: |
          gh pr list --state open --json number -q '.[].number' | while read -r pr; do
            echo "Merging PR #$pr"
            gh pr merge $pr --merge --admin
          done

