name: Simulate Concurrent PR Merges

on:
  workflow_dispatch:
  
env:
  GH_TOKEN: ${{ secrets.FRACTIONS_SECRET }}

permissions:
  contents: write
  pull-requests: write

jobs:
  simulate_concurrent_merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Merge pull requests
        run: |
          gh pr list --state open --json number -q '.[].number' | while read -r pr; do
            echo "Merging PR #$pr"
            gh pr checkout $pr
          #  git rebase origin/master
          #  git push --force-with-lease
            gh pr merge $pr --rebase --admin
          done

