name: Simulate Concurrent PR Merges

on:
  schedule:
    - cron: '30 18 * * *'  # Runs at 1:50 PM Eastern Time 

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  simulate_concurrent_merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Merge pull requests
        run: |
          gh pr list --state open --json number -q '.[].number' | while read -r pr; do
            echo "Merging PR #$pr"
            gh pr merge $pr --merge --admin
          done
