name: Simulate Concurrent PR Merges

on:
  schedule:
    - cron: '30 17 * * *'  # Runs at 1:30 PM Eastern Time 

permissions:
  contents: write
  pull-requests: write

jobs:
  simulate_concurrent_merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: GitHub CLI
        uses: actions/setup-gh@v2
        with:
          token: ${{ secrets.FRACTIONS_TOKEN }}

      - name: Merge pull requests
        run: |
          gh pr list --state open --json number -q '.[].number' | while read -r pr; do
            echo "Merging PR #$pr"
            gh pr merge $pr --merge --admin
          done
