name: Tag, build, test
on:
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: retrieve_tag
        run: |
          tag_pattern="[0-9]*.[0-9]*.[0-9]*"
          version_pattern="(.*)([0-9]+\.[0-9]+\.[0-9]+-?[a-zA-Z0-9]*)(.*)"
          tag=$(git for-each-ref --sort=-committerdate --count=1 --format '%(refname)' "refs/tags/$tag_pattern" | cut -d / -f 3-)
          tag_commit=$(git rev-list -n 1 $tag)
          echo "GitHub Run ID: ${{ github.run_id }} - Latest tag: $tag ($tag_commit)"
          echo "latest_tag=$tag" >> $GITHUB_ENV
