name: Test Workflow

on:
  workflow_run:
    workflows: ["Tag, build, test"]
    types:
      - completed

jobs:
  use-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Use Commit Hash and Run Test
        run: |
          COMMIT_HASH=${{ github.sha }}
          echo "Associate commit hash $COMMIT_HASH to test"
          sleep 10
